/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BallsPanel.java
 *
 * Created on Jan 9, 2010, 10:42:46 PM
 */

package openpkmnclient;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author matt
 */
public class BallsPanel extends javax.swing.JPanel {
   private ImageIcon normal;
   private ImageIcon status;
   private ImageIcon faint;
   private JLabel[] balls;
    /** Creates new form BallsPanel */
    public BallsPanel() {
        initComponents();
         normal = new ImageIcon(getClass().getResource(
                "/resources/balls/normal.png"), "Normal");
         status = new ImageIcon(getClass().getResource(
                "/resources/balls/status.png"), "Status");
         faint = new ImageIcon(getClass().getResource(
                "/resources/balls/faint.png"), "Fainted");
         balls = new JLabel[6];
         balls[0] = ball0;
         balls[1] = ball1;
         balls[2] = ball2;
         balls[3] = ball3;
         balls[4] = ball4;
         balls[5] = ball5;
    }

    public void setBalls(int numNormal, int numStatus, int numFainted) {
        int i = 0;
        while(numNormal > 0) {
            balls[i].setIcon(normal);
            numNormal--;
            i++;
        }
        while(numStatus > 0) {
            balls[i].setIcon(status);
            numStatus--;
            i++;
        }
        while(numFainted > 0) {
            balls[i].setIcon(faint);
            numFainted--;
            i++;
        }
    }

    public ImageIcon getNormal() {
        return normal;
    }

    public void setNormal(final ImageIcon normal) {
        this.normal = normal;
    }

    public ImageIcon getStatus() {
        return status;
    }

    public void setStatus(final ImageIcon status) {
        this.status = status;
    }

    public ImageIcon getFaint() {
        return faint;
    }

    public void setFaint(final ImageIcon faint) {
        this.faint = faint;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ball0 = new javax.swing.JLabel();
        ball1 = new javax.swing.JLabel();
        ball3 = new javax.swing.JLabel();
        ball2 = new javax.swing.JLabel();
        ball5 = new javax.swing.JLabel();
        ball4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(162, 15));
        setMinimumSize(new java.awt.Dimension(162, 15));
        setPreferredSize(new java.awt.Dimension(162, 15));

        ball0.setMaximumSize(new java.awt.Dimension(15, 15));
        ball0.setMinimumSize(new java.awt.Dimension(15, 15));
        ball0.setPreferredSize(new java.awt.Dimension(15, 15));

        ball1.setMaximumSize(new java.awt.Dimension(15, 15));
        ball1.setMinimumSize(new java.awt.Dimension(15, 15));
        ball1.setPreferredSize(new java.awt.Dimension(15, 15));

        ball3.setMaximumSize(new java.awt.Dimension(15, 15));
        ball3.setMinimumSize(new java.awt.Dimension(15, 15));
        ball3.setPreferredSize(new java.awt.Dimension(15, 15));

        ball2.setMaximumSize(new java.awt.Dimension(15, 15));
        ball2.setMinimumSize(new java.awt.Dimension(15, 15));
        ball2.setPreferredSize(new java.awt.Dimension(15, 15));

        ball5.setMaximumSize(new java.awt.Dimension(15, 15));
        ball5.setMinimumSize(new java.awt.Dimension(15, 15));
        ball5.setPreferredSize(new java.awt.Dimension(15, 15));

        ball4.setMaximumSize(new java.awt.Dimension(15, 15));
        ball4.setMinimumSize(new java.awt.Dimension(15, 15));
        ball4.setPreferredSize(new java.awt.Dimension(15, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ball0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ball1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ball2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ball3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ball4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ball5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ball0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ball1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ball5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ball4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ball2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ball3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ball0;
    private javax.swing.JLabel ball1;
    private javax.swing.JLabel ball2;
    private javax.swing.JLabel ball3;
    private javax.swing.JLabel ball4;
    private javax.swing.JLabel ball5;
    // End of variables declaration//GEN-END:variables
   
}
