CREATE TABLE `Battles` (
  `ID` int(11) NOT NULL auto_increment,
  `Winner_ID` int(11),
  `Loser_ID` int(11),
  `Challenger_ID` int(11) NOT NULL,
  `Defender_ID` int(11) NOT NULL,
  `challenger_team_id` int(11) NOT NULL,
  `challenger_starter` int(11) NOT NULL,
  `challenger_left` int(11),
  `defender_team_id` int(11) NOT NULL,
  `defender_starter` int(11) NOT NULL,
  `defender_left` int(11),
  `rules` int(11) NOT NULL,
  PRIMARY KEY  (`ID`),
  KEY `Battle_Challenger` (`Challenger_ID`),
  KEY `Battle_Defender` (`Defender_ID`),
  KEY `Battle_Loser` (`Loser_ID`),
  KEY `Battle_Winner` (`Winner_ID`),
  KEY `battle_challenger_team` (`challenger_team_id`),
  KEY `battle_challenger_starter` (`challenger_starter`),
  KEY `battle_defender_team` (`defender_team_id`),
  KEY `battle_defender_starter` (`defender_starter`),
  CONSTRAINT `Battle_Challenger` FOREIGN KEY (`Challenger_ID`) REFERENCES `Users` (`ID`),
  CONSTRAINT `battle_challenger_team` FOREIGN KEY (`challenger_team_id`) REFERENCES `Teams` (`ID`),
  CONSTRAINT `battle_challenger_starter` FOREIGN KEY (`challenger_starter`) REFERENCES `PKMN` (`ID`),
  CONSTRAINT `Battle_Defender` FOREIGN KEY (`Defender_ID`) REFERENCES `Users` (`ID`),
  CONSTRAINT `battle_defender_team` FOREIGN KEY (`defender_team_id`) REFERENCES `Teams` (`ID`),
  CONSTRAINT `battle_defender_starter` FOREIGN KEY (`defender_starter`) REFERENCES `PKMN` (`ID`),
  CONSTRAINT `Battle_Loser` FOREIGN KEY (`Loser_ID`) REFERENCES `Users` (`ID`),
  CONSTRAINT `Battle_Winner` FOREIGN KEY (`Winner_ID`) REFERENCES `Users` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=88 DEFAULT CHARSET=ascii