CREATE TABLE `Battle_state` (
  `ID` int(11) NOT NULL auto_increment,
  `turn_id` int(11) NOT NULL,
  `pkmn_id` int(11) NOT NULL,
  `eff_type_1` int(11),
  `eff_type_2` int(11),
  `current_attack` int(11),
  `current_defense` int(11),
  `current_speed` int(11),
  `current_special` int(11),
  `attack_mod` int(11),
  `defense_mod` int(11),
  `speed_mod` int(11),
  `special_mod` int(11),
  `evade_mod` int(11),
  `accuracy_mod` int(11),
  `special_halve` int(11),
  `physical_halve` int(11),
  `critical_hit_up` int(11),
  `mod_lock` int(11),
  `substitute` int(11),
  `toxic_turns` int(11),
  `confusion_turns` int(11),
  `seeded` int(11),
  `enraged` int(11),
  `flinched` int(11),
  `recharging` int(11),
  `disabled_selection` int(11),
  `disabled_turns` int(11),
  `trapping_damage` int(11),
  `trapping_move` int(11),
  `trapping_turns` int(11),
  `original_trapping_victim` int(11),
  `charging_move` int(11),
  `temp_invul` int(11),
  `rep_move_index` int(11),
  `damage_taken` int(11),
  `damage_is_counterable` int(11),
  `last_move_used` int(11),
  PRIMARY KEY  (`ID`),
  KEY `bs_turn` (`turn_id`),
  KEY `bs_pkmn` (`pkmn_id`),
  CONSTRAINT `bs_turn` FOREIGN KEY (`turn_id`) REFERENCES `Turns` (`ID`),
  CONSTRAINT `bs_pkmn` FOREIGN KEY (`pkmn_id`) REFERENCES `PKMN` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=88 DEFAULT CHARSET=ascii