#ifndef __OPENPKMN_SHARE_PREFERENCES__
#define __OPENPKMN_SHARE_PREFERENCES__

enum User_Preferences { SLEEP_CLAUSE = 0x00000001,
			FREEZE_CLAUSE = 0x00000002,
			MEW_DISALLOWED =  0x00000004,
			MEWTWO_DISALLOWED = 0x00000008,
			EVADE_MOVES_DISALLOWED = 0x00000010,
			OHKO_MOVES_DISALLOWED = 0x00000020,
			GS_MOVES_DISALLOWED = 0x00000040,
			TM_MOVES_DISALLOWED = 0x00000080,
			ILLEGAL_MOVES_DISALLOWED = 0x00000100,
			ILLEGAL_LEVELS_DISALLOWED = 0x00000200,
			ILLEGAL_STATS_DISALLOWED = 0x00000400,
			DUPLICATE_PKMN_DISALLOWED = 0x00000800 };

enum Team_Characteristics { HOLDS_TO_MEW_DISALLOWED = MEW_DISALLOWED,
			    HOLDS_TO_MEWTWO_DISALLOWED = MEWTWO_DISALLOWED,
			    HOLDS_TO_EVADE_MOVES_DISALLOWED =
			    EVADE_MOVES_DISALLOWED,
			    HOLDS_TO_OHKO_MOVES_DISALLOWED =
			    OHKO_MOVES_DISALLOWED,
			    HOLDS_TO_GS_MOVES_DISALLOWED = GS_MOVES_DISALLOWED,
			    HOLDS_TO_TM_MOVES_DISALLOWED = TM_MOVES_DISALLOWED,
			    HOLDS_TO_ILLEGAL_MOVES_DISALLOWED =
			    ILLEGAL_MOVES_DISALLOWED,
			    HOLDS_TO_ILLEGAL_LEVELS_DISALLOWED =
			    ILLEGAL_LEVELS_DISALLOWED,
			    HOLDS_TO_ILLEGAL_STATS_DISALLOWED =
			    ILLEGAL_STATS_DISALLOWED,
			    HOLDS_TO_DUPLICATE_PKMN_DISALLOWED =
			    DUPLICATE_PKMN_DISALLOWED };


#define PKMN_RESTRICTIONS (MEW_DISALLOWED |  MEWTWO_DISALLOWED)
#define MOVE_RESTRICTIONS (OHKO_MOVES_DISALLOWED | EVADE_MOVES_DISALLOWED)
#define LEARNING_RESTRICTIONS (GS_MOVES_DISALLOWED | TM_MOVES_DISALLOWED | \
			       ILLEGAL_MOVES_DISALLOWED )
#endif


